//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bibliotheque_app
    {
        public int id_app { get; set; }
        public int id_bib { get; set; }
        public Nullable<System.DateTime> date_telechargement { get; set; }
    
        public virtual bibliotheque bibliotheque { get; set; }
        public virtual u_application u_application { get; set; }
    }
}
