//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class profinsemEntities2 : DbContext
    {
        public profinsemEntities2()
            : base("name=profinsemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bibliotheque> bibliotheque { get; set; }
        public virtual DbSet<Bibliotheque_app> Bibliotheque_app { get; set; }
        public virtual DbSet<categorie> categorie { get; set; }
        public virtual DbSet<review> review { get; set; }
        public virtual DbSet<u_application> u_application { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
    }
}
