//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public u_application()
        {
            this.Bibliotheque_app = new HashSet<Bibliotheque_app>();
            this.review = new HashSet<review>();
        }
    
        public int id_app { get; set; }
        public string nom_app { get; set; }
        public Nullable<int> nombre_telechargement { get; set; }
        public Nullable<System.DateTime> date_ajout { get; set; }
        public Nullable<int> categorie { get; set; }
        public Nullable<int> id_user { get; set; }
        public string app_img { get; set; }
        public string u_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bibliotheque_app> Bibliotheque_app { get; set; }
        public virtual categorie categorie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> review { get; set; }
        public virtual utilisateur utilisateur { get; set; }
    }
}
