//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dev.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Pilote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pilote()
        {
            this.Vol = new HashSet<Vol>();
        }
    
        public int num_pil { get; set; }
        [Required]
        public string nom_pil { get; set; }
        [Required]
        [MaxLength(10)]
        public string prenom_pil { get; set; }
        [MaxLength(10)]
        [Required]
        public string ville_domicile { get; set; }
        [Required]
        [Phone]
        public int num_tel { get; set; }
        
        [Required]
        [EmailAddress]
        
        public string email { get; set; }
        [Required]
        public Nullable<int> salaire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vol> Vol { get; set; }
    }
}
