//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dev.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vol
    {
        public int num_vol { get; set; }
        [Required]
        public int num_pil { get; set; }
        [Required]
        public int num_av { get; set; }
        [Required]
        public string ville_depart { get; set; }
        [Required]
        public string ville_arrive { get; set; }
        [Required]
        
        public System.DateTime date_depart { get; set; }
        public System.DateTime date_arrivee { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual Pilote Pilote { get; set; }
    }
}
