//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetfinsem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.Review = new HashSet<Review>();
            this.BIBLIO = new HashSet<BIBLIO>();
        }
    
        public int idapp { get; set; }
        public int idprop { get; set; }
        public string nomapp { get; set; }
        public System.DateTime date_creation { get; set; }
        public Nullable<int> nombre_telechargement { get; set; }
        public int idcategorie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Review { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIBLIO> BIBLIO { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual User User { get; set; }
    }
}
